package com.shahin.buildsrc


object Versions {
    const val coreKtx = "1.7.0"
    const val appCompat = "1.4.2"
    const val legacySupport = "1.0.0"
    const val navigation = "2.4.2"
    const val gradle = "7.1.3"
    const val ktlint = "0.37.2"
    const val kotlin = "1.5.30"
    const val coroutines = "1.5.2"
    const val gradleVersions = "0.39.0"
    const val lifecycleVersion = "2.2.0"
    const val archTest = "2.1.0"
    const val material = "1.6.1"
    const val annotation = "1.3.0"
    const val constraintLayout = "2.1.4"
    const val room = "2.3.0"
    const val paging = "3.0.1"
    const val workManager = "2.5.0"
    const val dagger = "2.40"
    const val hilt = "2.41"
    const val okHttp = "4.9.2"
    const val gson = "2.8.7"
    const val retrofit = "2.9.0"
    const val moshi = "2.8.1"
    const val stetho = "1.6.0"
    const val glide = "4.12.0"
    const val lottie = "3.4.1"
    const val indicator = "4.2"
    const val playServicesLocation = "19.0.1"
    const val playServicesMaps = "18.0.2"
    const val junit = "4.13.2"
    const val extJunit = "1.1.3"
    const val espresso = "3.4.0"
    const val testRunner = "1.2.0"
    const val testCore = "1.4.0"
    const val mockitoKotlin = "4.0.0"
    const val mockitoCore = "4.0.0"
    const val robolectric = "4.6.1"
    const val hamcrest = "2.2"
}